sudo: false

addons:
  postgresql: "9.4"
services:
  - postgresql

env:
- NODE_ENV=test

before_script:
  - psql -c 'create database database_test;' -U postgres
  - npm run migrate


language: node_js
node_js:
  - "5.0"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"
